### ISSUE TITLE
Graph Execution Error

### ISSUE THREAD

**Issue by ShadowVicky** [ShubhJaroria/Transfer-Learning-YAMNet#1]
I am getting graph execution error ? 
How can i fix it?

**Comment by ShubhJaroria** [comment]
Can you post the error message and the trace? Thanks.

**Comment by ShadowVicky** [comment]
Epoch 1/10
---------------------------------------------------------------------------
NotFoundError                             Traceback (most recent call last)
[<ipython-input-48-0b668ddbda3a>](https://localhost:8080/#) in <cell line: 1>()
----> 1 history = my_modelb.fit(train_ds,
      2                        epochs=10,
      3                        validation_data=val_ds,
      4                        callbacks=callback)

1 frames
[/usr/local/lib/python3.10/dist-packages/tensorflow/python/eager/execute.py](https://localhost:8080/#) in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     51   try:
     52     ctx.ensure_initialized()
---> 53     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
     54                                         inputs, attrs, num_outputs)
     55   except core._NotOkStatusException as e:

NotFoundError: Graph execution error:

/content/drive/MyDrive/Enviromental_Soun_Classification/8K_DATA_FOR_ESC/audio/double167.wav; No such file or directory
	 [[{{node ReadFile}}]]
	 [[IteratorGetNext]] [Op:__inference_train_function_20429]

**Comment by ShubhJaroria** [comment]
It probably has something to do with the tensorflow installation on your machine. Try running the code on Google Colab or reinstalling tensorflow.

**Comment by ShadowVicky** [comment]
I tried but , but i can;t fix it
BTW i am trying this model for my own data?
